#

add_newline = false

[line_break]
disabled = true

[character]
success_symbol = ">"

[battery]
disabled = true

[[battery.display]]
threshold = 15
style = "bold red"

[directory]
truncation_length = 10
truncate_to_repo = true

[cmd_duration]
min_time = 5000
show_milliseconds = false

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_status]
disabled = true

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
